export default [
  {
    id: "profile-post-1",
    uid: "1",
    text: "Just finished reading an amazing book about AI ethics! Highly recommend it to everyone interested in technology.",
    timestamp: Date.now() - 86400000, // 1 day ago
    type: "profile",
  },
  {
    id: "profile-post-2",
    uid: "1",
    text: "Beautiful sunset today. Sometimes we need to pause and appreciate the simple things in life.",
    timestamp: Date.now() - 172800000, // 2 days ago
    type: "profile",
  },
  {
    id: "profile-post-3",
    uid: "2",
    text: "Working on a new React project. The new features are really exciting!",
    timestamp: Date.now() - 43200000, // 12 hours ago
    type: "profile",
  },
  {
    id: "profile-post-4",
    uid: "2",
    text: "Just had the best coffee in town. If you're in the area, you have to try this place!",
    timestamp: Date.now() - 129600000, // 1.5 days ago
    type: "profile",
  },
  {
    id: "profile-post-5",
    uid: "3",
    text: "Learning a new programming language. It's challenging but rewarding!",
    timestamp: Date.now() - 21600000, // 6 hours ago
    type: "profile",
  },
  {
    id: "profile-post-6",
    uid: "3",
    text: "Weekend hiking trip was amazing. Nature always helps me recharge.",
    timestamp: Date.now() - 86400000, // 1 day ago
    type: "profile",
  },
  {
    id: "profile-post-7",
    uid: "4",
    text: "Just released a new version of my open source project. Check it out!",
    timestamp: Date.now() - 7200000, // 2 hours ago
    type: "profile",
  },
  {
    id: "profile-post-8",
    uid: "4",
    text: "Thinking about the future of web development. So many exciting possibilities!",
    timestamp: Date.now() - 86400000, // 1 day ago
    type: "profile",
  },
  {
    id: "profile-post-9",
    uid: "5",
    text: "Started a new painting today. The colors are coming together beautifully.",
    timestamp: Date.now() - 3600000, // 1 hour ago
    type: "profile",
  },
  {
    id: "profile-post-10",
    uid: "5",
    text: "Visited the art museum yesterday. So much inspiration!",
    timestamp: Date.now() - 172800000, // 2 days ago
    type: "profile",
  },
  // Add 50 more profile posts from various users
  ...Array.from({ length: 50 }, (_, i) => ({
    id: `profile-post-extra-${i + 11}`,
    uid: `${(i % 26) + 1}`, // Distribute across users 1-26
    text: `Profile post content ${i + 1} from user ${
      (i % 26) + 1
    }. This is sample content to populate the feed.`,
    timestamp: Date.now() - i * 3600000, // Stagger timestamps
    type: "profile",
  })),
  // Add feed posts
  ...Array.from({ length: 30 }, (_, i) => ({
    id: `feed-post-${i + 1}`,
    uid: `${(i % 26) + 1}`,
    text: `Feed post ${
      i + 1
    }: Sharing something interesting with my followers!`,
    timestamp: Date.now() - i * 1800000, // Stagger timestamps
    type: "feed",
  })),
  // Add popular posts
  ...Array.from({ length: 20 }, (_, i) => ({
    id: `popular-post-${i + 1}`,
    uid: `${(i % 26) + 1}`,
    text: `Popular post ${i + 1}: This is trending right now!`,
    timestamp: Date.now() - i * 3600000,
    type: "popular",
  })),
  // Add notification posts
  ...Array.from({ length: 15 }, (_, i) => ({
    id: `notification-${i + 1}`,
    uid: "system",
    text: `Notification ${i + 1}: You have a new message or update.`,
    timestamp: Date.now() - i * 7200000,
    type: "notification",
    subtype:
      i % 5 === 0
        ? "like"
        : i % 5 === 1
        ? "follow"
        : i % 5 === 2
        ? "comment"
        : i % 5 === 3
        ? "mention"
        : "trending",
  })),
  // Add messages for Team Discussion (private-group)
  {
    id: "team-discussion-1",
    uid: "1",
    text: "Hey team, let's discuss the project timeline",
    timestamp: Date.now() - 3600000,
    type: "chat",
    room: "private-group-1",
  },
  {
    id: "team-discussion-2",
    uid: "0",
    text: "I think we can finish by next Friday",
    timestamp: Date.now() - 1800000,
    type: "chat",
    room: "private-group-1",
  },
  {
    id: "team-discussion-3",
    uid: "2",
    text: "Sounds good. I'll have my part ready by Wednesday",
    timestamp: Date.now() - 600000,
    type: "chat",
    room: "private-group-1",
  },
  // Add more chat messages for various rooms
  ...Array.from({ length: 20 }, (_, i) => ({
    id: `chat-message-${i + 1}`,
    uid: `${(i % 26) + 1}`,
    text: `Chat message ${i + 1} in the conversation.`,
    timestamp: Date.now() - i * 300000,
    type: "chat",
    room:
      i % 3 === 0
        ? "public-group-1"
        : i % 3 === 1
        ? "public-group-2"
        : "public-group-3",
  })),
  // Add profile posts for current user
  {
    id: "profile-post-current-1",
    uid: "0",
    text: "Welcome to my profile! I'm excited to connect with everyone on this platform.",
    timestamp: Date.now() - 3600000, // 1 hour ago
    type: "profile",
  },
  {
    id: "profile-post-current-2",
    uid: "0",
    text: "Working on some exciting new features for our project. Can't wait to share more soon!",
    timestamp: Date.now() - 86400000, // 1 day ago
    type: "profile",
  },
  {
    id: "profile-post-current-3",
    uid: "0",
    text: "Just finished a great workout. Staying active is important for both body and mind.",
    timestamp: Date.now() - 172800000, // 2 days ago
    type: "profile",
  },
  // Profile posts for user 0
  {
    id: "1",
    uid: "0",
    text: "Just finished my new project! Feeling accomplished!",
    timestamp: Date.now() - 2 * 60 * 60 * 1000,
    type: "profile",
  },
  // Replies to post 1
  {
    id: "60",
    uid: "1",
    text: "Congratulations! What kind of project was it?",
    timestamp: Date.now() - 110 * 60 * 1000,
    type: "profile",
    parentId: "1",
  },
  {
    id: "61",
    uid: "0",
    text: "It's a social media app with real-time chat features!",
    timestamp: Date.now() - 105 * 60 * 1000,
    type: "profile",
    parentId: "1",
  },
  {
    id: "62",
    uid: "2",
    text: "That sounds awesome! Can't wait to try it out.",
    timestamp: Date.now() - 100 * 60 * 1000,
    type: "profile",
    parentId: "1",
  },
  {
    id: "63",
    uid: "3",
    text: "Great work! How long did it take you to build?",
    timestamp: Date.now() - 95 * 60 * 1000,
    type: "profile",
    parentId: "1",
  },
  {
    id: "64",
    uid: "0",
    text: "About 3 months of dedicated work. The real-time features were the most challenging part.",
    timestamp: Date.now() - 90 * 60 * 1000,
    type: "profile",
    parentId: "1",
  },
  {
    id: "65",
    uid: "1",
    text: "Impressive! What tech stack did you use?",
    timestamp: Date.now() - 85 * 60 * 1000,
    type: "profile",
    parentId: "1",
  },
  {
    id: "66",
    uid: "0",
    text: "React for the frontend, Node.js for the backend, and Socket.io for real-time communication.",
    timestamp: Date.now() - 80 * 60 * 1000,
    type: "profile",
    parentId: "1",
  },
  {
    id: "67",
    uid: "2",
    text: "Solid choices! Are you planning to open source it?",
    timestamp: Date.now() - 75 * 60 * 1000,
    type: "profile",
    parentId: "1",
  },
  {
    id: "68",
    uid: "0",
    text: "Maybe in the future! Right now I'm focusing on polishing the user experience.",
    timestamp: Date.now() - 70 * 60 * 1000,
    type: "profile",
    parentId: "1",
  },
  {
    id: "2",
    uid: "0",
    text: "Beautiful day for a hike 🏞️",
    timestamp: Date.now() - 24 * 60 * 60 * 1000,
    type: "profile",
  },
  {
    id: "3",
    uid: "0",
    text: "Learning React has been amazing!",
    timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    type: "profile",
  },
  {
    id: "18",
    uid: "0",
    text: "Working on some exciting new features for the app!",
    timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
    type: "profile",
  },
  {
    id: "19",
    uid: "0",
    text: "Just read an incredible book about design patterns",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
    type: "profile",
  },
  {
    id: "20",
    uid: "0",
    text: "Weekend coding session with friends 🚀",
    timestamp: Date.now() - 6 * 24 * 60 * 60 * 1000,
    type: "profile",
  },
  // Replies to post 20
  {
    id: "90",
    uid: "1",
    text: "That sounds like fun! What were you working on?",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
    type: "profile",
    parentId: "20",
  },
  {
    id: "91",
    uid: "0",
    text: "We were building a new feature for our chat app - real-time notifications!",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000,
    type: "profile",
    parentId: "20",
  },
  {
    id: "92",
    uid: "2",
    text: "Nice! Did you use WebSockets or Server-Sent Events?",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000 + 45 * 60 * 1000,
    type: "profile",
    parentId: "20",
  },
  {
    id: "93",
    uid: "0",
    text: "We went with WebSockets using Socket.io. It's been working great so far!",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000 + 60 * 60 * 1000,
    type: "profile",
    parentId: "20",
  },
  {
    id: "94",
    uid: "3",
    text: "Socket.io is awesome! The fallback mechanisms are really useful for production apps.",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000 + 75 * 60 * 1000,
    type: "profile",
    parentId: "20",
  },
  {
    id: "95",
    uid: "1",
    text: "How did you handle reconnection logic? That's always the tricky part.",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000 + 90 * 60 * 1000,
    type: "profile",
    parentId: "20",
  },
  {
    id: "96",
    uid: "0",
    text: "We used the built-in reconnection with exponential backoff. Also added some UI indicators for connection status.",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000 + 105 * 60 * 1000,
    type: "profile",
    parentId: "20",
  },
  {
    id: "97",
    uid: "4",
    text: "Did you face any issues with scaling? WebSockets can be tricky with multiple servers.",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000 + 120 * 60 * 1000,
    type: "profile",
    parentId: "20",
  },
  {
    id: "98",
    uid: "0",
    text: "We're using Redis for pub/sub between servers. It's working well for our current scale!",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000 + 135 * 60 * 1000,
    type: "profile",
    parentId: "20",
  },
  {
    id: "99",
    uid: "2",
    text: "Redis is a solid choice. We use it for session storage too.",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000 + 150 * 60 * 1000,
    type: "profile",
    parentId: "20",
  },
  {
    id: "100",
    uid: "5",
    text: "Sounds like a productive weekend! Wish I could have joined.",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000 + 165 * 60 * 1000,
    type: "profile",
    parentId: "20",
  },
  {
    id: "101",
    uid: "0",
    text: "Next time for sure! We're planning another session next month.",
    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000 + 180 * 60 * 1000,
    type: "profile",
    parentId: "20",
  },

  // Profile posts for user 1
  {
    id: "21",
    uid: "1",
    text: "My new photography portfolio is live!",
    timestamp: Date.now() - 1 * 60 * 60 * 1000,
    type: "profile",
  },
  {
    id: "22",
    uid: "1",
    text: "Exploring new coffee shops in the city ☕",
    timestamp: Date.now() - 12 * 60 * 60 * 1000,
    type: "profile",
  },
  {
    id: "23",
    uid: "1",
    text: "Just finished a marathon coding session",
    timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
    type: "profile",
  },

  // Profile posts for user 2
  {
    id: "24",
    uid: "2",
    text: "Launching my startup next month! Stay tuned",
    timestamp: Date.now() - 45 * 60 * 1000,
    type: "profile",
  },
  {
    id: "25",
    uid: "2",
    text: "The future of AI is here and it's incredible",
    timestamp: Date.now() - 8 * 60 * 60 * 1000,
    type: "profile",
  },
  {
    id: "26",
    uid: "2",
    text: "Working remotely from the mountains today",
    timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    type: "profile",
  },

  // Profile posts for user 3
  {
    id: "27",
    uid: "3",
    text: "Teaching my dog new tricks 🐕",
    timestamp: Date.now() - 30 * 60 * 1000,
    type: "profile",
  },
  {
    id: "28",
    uid: "3",
    text: "Just bought a new gaming setup!",
    timestamp: Date.now() - 6 * 60 * 60 * 1000,
    type: "profile",
  },
  {
    id: "29",
    uid: "3",
    text: "Weekend road trip was amazing!",
    timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
    type: "profile",
  },

  // Feed posts from other users
  {
    id: "4",
    uid: "1",
    text: "Check out this cool article I found!",
    timestamp: Date.now() - 60 * 60 * 1000,
    type: "feed",
  },
  // Replies to post 4
  {
    id: "70",
    uid: "0",
    text: "What's the article about?",
    timestamp: Date.now() - 55 * 60 * 1000,
    type: "feed",
    parentId: "4",
  },
  {
    id: "71",
    uid: "1",
    text: "It's about the future of AI in web development. Really fascinating stuff!",
    timestamp: Date.now() - 50 * 60 * 1000,
    type: "feed",
    parentId: "4",
  },
  {
    id: "72",
    uid: "2",
    text: "Can you share the link? I'd love to read it.",
    timestamp: Date.now() - 45 * 60 * 1000,
    type: "feed",
    parentId: "4",
  },
  {
    id: "73",
    uid: "1",
    text: "Sure! Here it is: https://example.com/ai-web-dev-future",
    timestamp: Date.now() - 40 * 60 * 1000,
    type: "feed",
    parentId: "4",
  },
  {
    id: "74",
    uid: "3",
    text: "Thanks for sharing! I've been looking for good resources on this topic.",
    timestamp: Date.now() - 35 * 60 * 1000,
    type: "feed",
    parentId: "4",
  },
  {
    id: "75",
    uid: "0",
    text: "Just read it. The part about AI-assisted debugging is mind-blowing!",
    timestamp: Date.now() - 30 * 60 * 1000,
    type: "feed",
    parentId: "4",
  },
  {
    id: "76",
    uid: "1",
    text: "Right? I can't wait to see these tools become mainstream.",
    timestamp: Date.now() - 25 * 60 * 1000,
    type: "feed",
    parentId: "4",
  },
  {
    id: "77",
    uid: "2",
    text: "The ethical considerations section was particularly thought-provoking.",
    timestamp: Date.now() - 20 * 60 * 1000,
    type: "feed",
    parentId: "4",
  },
  {
    id: "78",
    uid: "1",
    text: "Absolutely. We need to be careful about how we implement these technologies.",
    timestamp: Date.now() - 15 * 60 * 1000,
    type: "feed",
    parentId: "4",
  },
  {
    id: "5",
    uid: "2",
    text: "Just released a new version of my app!",
    timestamp: Date.now() - 3 * 60 * 60 * 1000,
    type: "feed",
  },
  {
    id: "6",
    uid: "3",
    text: "Anyone up for coffee this weekend?",
    timestamp: Date.now() - 5 * 60 * 60 * 1000,
    type: "feed",
  },
  {
    id: "30",
    uid: "1",
    text: "The sunset tonight was absolutely breathtaking 🌅",
    timestamp: Date.now() - 7 * 60 * 60 * 1000,
    type: "feed",
  },
  {
    id: "31",
    uid: "2",
    text: "Just hit 10k users on our platform! 🎉",
    timestamp: Date.now() - 10 * 60 * 60 * 1000,
    type: "feed",
  },
  {
    id: "32",
    uid: "3",
    text: "Learning guitar during quarantine",
    timestamp: Date.now() - 15 * 60 * 60 * 1000,
    type: "feed",
  },
  {
    id: "33",
    uid: "4",
    text: "My garden is finally blooming! 🌸",
    timestamp: Date.now() - 20 * 60 * 60 * 1000,
    type: "feed",
  },
  {
    id: "34",
    uid: "5",
    text: "Working on a new open source project",
    timestamp: Date.now() - 25 * 60 * 60 * 1000,
    type: "feed",
  },

  // Recommendations
  {
    id: "7",
    uid: "system",
    text: "Breaking: New framework released that will change everything!",
    timestamp: Date.now() - 30 * 60 * 1000,
    type: "recommendation",
  },
  {
    id: "8",
    uid: "system",
    text: "10 UI/UX principles you should know in 2024",
    timestamp: Date.now() - 2 * 60 * 60 * 1000,
    type: "recommendation",
  },
  {
    id: "9",
    uid: "system",
    text: "Join our virtual meetup next week!",
    timestamp: Date.now() - 24 * 60 * 60 * 1000,
    type: "recommendation",
  },
  {
    id: "35",
    uid: "system",
    text: "Top 5 productivity apps you should try",
    timestamp: Date.now() - 3 * 60 * 60 * 1000,
    type: "recommendation",
  },
  {
    id: "36",
    uid: "system",
    text: "Local event: Tech conference this Saturday",
    timestamp: Date.now() - 5 * 60 * 60 * 1000,
    type: "recommendation",
  },
  {
    id: "37",
    uid: "system",
    text: "New study shows benefits of meditation for developers",
    timestamp: Date.now() - 8 * 60 * 60 * 1000,
    type: "recommendation",
  },

  // Chat messages - updated to use new room IDs
  {
    id: "10",
    uid: "1",
    text: "Hey, how are you doing?",
    timestamp: Date.now() - 2 * 60 * 60 * 1000,
    type: "chat",
    room: "private-1-0",
  },
  {
    id: "11",
    uid: "0",
    text: "I'm good! Working on the new project.",
    timestamp: Date.now() - 118 * 60 * 1000,
    type: "chat",
    room: "private-1-0",
  },
  {
    id: "12",
    uid: "1",
    text: "That sounds exciting! Let me know if you need help.",
    timestamp: Date.now() - 115 * 60 * 1000,
    type: "chat",
    room: "private-1-0",
  },
  {
    id: "38",
    uid: "0",
    text: "Thanks! I'll definitely reach out if I get stuck",
    timestamp: Date.now() - 110 * 60 * 1000,
    type: "chat",
    room: "private-1-0",
  },
  {
    id: "39",
    uid: "1",
    text: "Great! Looking forward to seeing what you build",
    timestamp: Date.now() - 105 * 60 * 1000,
    type: "chat",
    room: "private-1-0",
  },
  // Add more replies to make focused view more interesting
  {
    id: "50",
    uid: "0",
    text: "Actually, I could use some help with the authentication part.",
    timestamp: Date.now() - 100 * 60 * 1000,
    type: "chat",
    room: "private-1-0",
  },
  {
    id: "51",
    uid: "1",
    text: "Sure! I've worked with OAuth before. What's giving you trouble?",
    timestamp: Date.now() - 95 * 60 * 1000,
    type: "chat",
    room: "private-1-0",
  },
  {
    id: "52",
    uid: "0",
    text: "The token refresh flow is a bit confusing. How do you handle expired tokens?",
    timestamp: Date.now() - 90 * 60 * 1000,
    type: "chat",
    room: "private-1-0",
  },
  {
    id: "53",
    uid: "1",
    text: "You need to implement an interceptor that catches 401 errors and automatically refreshes the token.",
    timestamp: Date.now() - 85 * 60 * 1000,
    type: "chat",
    room: "private-1-0",
  },
  {
    id: "54",
    uid: "0",
    text: "That makes sense! I'll try that approach.",
    timestamp: Date.now() - 80 * 60 * 1000,
    type: "chat",
    room: "private-1-0",
  },
  {
    id: "55",
    uid: "1",
    text: "Let me know if you need code examples. I can share some from my previous projects.",
    timestamp: Date.now() - 75 * 60 * 1000,
    type: "chat",
    room: "private-1-0",
  },
  {
    id: "56",
    uid: "0",
    text: "That would be amazing! Thank you so much!",
    timestamp: Date.now() - 70 * 60 * 1000,
    type: "chat",
    room: "private-1-0",
  },

  // Notifications
  {
    id: "13",
    uid: "system",
    text: "Alice Johnson liked your post",
    timestamp: Date.now() - 5 * 60 * 1000,
    type: "notification",
    subtype: "like",
  },
  {
    id: "14",
    uid: "system",
    text: "Bob Smith started following you",
    timestamp: Date.now() - 15 * 60 * 1000,
    type: "notification",
    subtype: "follow",
  },
  {
    id: "15",
    uid: "system",
    text: "Carol Davis commented on your photo: 'Great shot!'",
    timestamp: Date.now() - 45 * 60 * 1000,
    type: "notification",
    subtype: "comment",
  },
  {
    id: "40",
    uid: "system",
    text: "David Wilson shared your post",
    timestamp: Date.now() - 55 * 60 * 1000,
    type: "notification",
    subtype: "share",
  },
  {
    id: "41",
    uid: "system",
    text: "Emma Brown mentioned you in a comment",
    timestamp: Date.now() - 65 * 60 * 1000,
    type: "notification",
    subtype: "mention",
  },
  {
    id: "42",
    uid: "system",
    text: "Frank Miller sent you a friend request",
    timestamp: Date.now() - 75 * 60 * 1000,
    type: "notification",
    subtype: "friend-request",
  },

  // Popular posts
  {
    id: "16",
    uid: "4",
    text: "This new framework is trending everywhere! #webdev",
    timestamp: Date.now() - 60 * 60 * 1000,
    type: "popular",
  },
  // Replies to post 16
  {
    id: "80",
    uid: "0",
    text: "Which framework are you talking about?",
    timestamp: Date.now() - 55 * 60 * 1000,
    type: "popular",
    parentId: "16",
  },
  {
    id: "81",
    uid: "4",
    text: "It's called 'NovaJS' - it's gaining a lot of traction in the community.",
    timestamp: Date.now() - 50 * 60 * 1000,
    type: "popular",
    parentId: "16",
  },
  {
    id: "82",
    uid: "1",
    text: "I've heard about it! The performance benchmarks are impressive.",
    timestamp: Date.now() - 45 * 60 * 1000,
    type: "popular",
    parentId: "16",
  },
  {
    id: "83",
    uid: "2",
    text: "Has anyone tried it in production yet?",
    timestamp: Date.now() - 40 * 60 * 1000,
    type: "popular",
    parentId: "16",
  },
  {
    id: "84",
    uid: "4",
    text: "Yes, several companies have started adopting it. The migration tools are supposedly really good.",
    timestamp: Date.now() - 35 * 60 * 1000,
    type: "popular",
    parentId: "16",
  },
  {
    id: "85",
    uid: "3",
    text: "I'm skeptical about new frameworks. Remember when everyone jumped on the last 'hot' framework?",
    timestamp: Date.now() - 30 * 60 * 1000,
    type: "popular",
    parentId: "16",
  },
  {
    id: "86",
    uid: "1",
    text: "That's a fair point, but the core team behind this one has a good track record.",
    timestamp: Date.now() - 25 * 60 * 1000,
    type: "popular",
    parentId: "16",
  },
  {
    id: "87",
    uid: "0",
    text: "I think I'll wait for version 1.0 before considering it for my projects.",
    timestamp: Date.now() - 20 * 60 * 1000,
    type: "popular",
    parentId: "16",
  },
  {
    id: "88",
    uid: "4",
    text: "Smart approach! The ecosystem is still developing.",
    timestamp: Date.now() - 15 * 60 * 1000,
    type: "popular",
    parentId: "16",
  },
  {
    id: "17",
    uid: "5",
    text: "Breakthrough in machine learning algorithms announced today",
    timestamp: Date.now() - 2 * 60 * 60 * 1000,
    type: "popular",
  },
  {
    id: "43",
    uid: "6",
    text: "Viral recipe for the best chocolate chip cookies!",
    timestamp: Date.now() - 3 * 60 * 60 * 1000,
    type: "popular",
  },
  {
    id: "44",
    uid: "7",
    text: "The most beautiful hiking trails in the country",
    timestamp: Date.now() - 4 * 60 * 60 * 1000,
    type: "popular",
  },
  {
    id: "45",
    uid: "8",
    text: "How I built a million-dollar business in 6 months",
    timestamp: Date.now() - 6 * 60 * 60 * 1000,
    type: "popular",
  },
  {
    id: "46",
    uid: "9",
    text: "The secret to maintaining work-life balance",
    timestamp: Date.now() - 8 * 60 * 60 * 1000,
    type: "popular",
  },
  {
    id: "47",
    uid: "10",
    text: "My journey from zero to 100k followers on social media",
    timestamp: Date.now() - 12 * 60 * 60 * 1000,
    type: "popular",
  },
];
