export default [
    // Profile posts for user 0
    {
      id: "1",
      uid: "0",
      text: "Just finished my new project! Feeling accomplished!",
      timestamp: Date.now() - 2 * 60 * 60 * 1000,
      type: "profile",
    },
    {
      id: "2",
      uid: "0",
      text: "Beautiful day for a hike 🏞️",
      timestamp: Date.now() - 24 * 60 * 60 * 1000,
      type: "profile",
    },
    {
      id: "3",
      uid: "0",
      text: "Learning React has been amazing!",
      timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
      type: "profile",
    },
    {
      id: "18",
      uid: "0",
      text: "Working on some exciting new features for the app!",
      timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
      type: "profile",
    },
    {
      id: "19",
      uid: "0",
      text: "Just read an incredible book about design patterns",
      timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
      type: "profile",
    },
    {
      id: "20",
      uid: "0",
      text: "Weekend coding session with friends 🚀",
      timestamp: Date.now() - 6 * 24 * 60 * 60 * 1000,
      type: "profile",
    },

    // Profile posts for user 1
    {
      id: "21",
      uid: "1",
      text: "My new photography portfolio is live!",
      timestamp: Date.now() - 1 * 60 * 60 * 1000,
      type: "profile",
    },
    {
      id: "22",
      uid: "1",
      text: "Exploring new coffee shops in the city ☕",
      timestamp: Date.now() - 12 * 60 * 60 * 1000,
      type: "profile",
    },
    {
      id: "23",
      uid: "1",
      text: "Just finished a marathon coding session",
      timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
      type: "profile",
    },

    // Profile posts for user 2
    {
      id: "24",
      uid: "2",
      text: "Launching my startup next month! Stay tuned",
      timestamp: Date.now() - 45 * 60 * 1000,
      type: "profile",
    },
    {
      id: "25",
      uid: "2",
      text: "The future of AI is here and it's incredible",
      timestamp: Date.now() - 8 * 60 * 60 * 1000,
      type: "profile",
    },
    {
      id: "26",
      uid: "2",
      text: "Working remotely from the mountains today",
      timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
      type: "profile",
    },

    // Profile posts for user 3
    {
      id: "27",
      uid: "3",
      text: "Teaching my dog new tricks 🐕",
      timestamp: Date.now() - 30 * 60 * 1000,
      type: "profile",
    },
    {
      id: "28",
      uid: "3",
      text: "Just bought a new gaming setup!",
      timestamp: Date.now() - 6 * 60 * 60 * 1000,
      type: "profile",
    },
    {
      id: "29",
      uid: "3",
      text: "Weekend road trip was amazing!",
      timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
      type: "profile",
    },

    // Feed posts from other users
    {
      id: "4",
      uid: "1",
      text: "Check out this cool article I found!",
      timestamp: Date.now() - 60 * 60 * 1000,
      type: "feed",
    },
    {
      id: "5",
      uid: "2",
      text: "Just released a new version of my app!",
      timestamp: Date.now() - 3 * 60 * 60 * 1000,
      type: "feed",
    },
    {
      id: "6",
      uid: "3",
      text: "Anyone up for coffee this weekend?",
      timestamp: Date.now() - 5 * 60 * 60 * 1000,
      type: "feed",
    },
    {
      id: "30",
      uid: "1",
      text: "The sunset tonight was absolutely breathtaking 🌅",
      timestamp: Date.now() - 7 * 60 * 60 * 1000,
      type: "feed",
    },
    {
      id: "31",
      uid: "2",
      text: "Just hit 10k users on our platform! 🎉",
      timestamp: Date.now() - 10 * 60 * 60 * 1000,
      type: "feed",
    },
    {
      id: "32",
      uid: "3",
      text: "Learning guitar during quarantine",
      timestamp: Date.now() - 15 * 60 * 60 * 1000,
      type: "feed",
    },
    {
      id: "33",
      uid: "4",
      text: "My garden is finally blooming! 🌸",
      timestamp: Date.now() - 20 * 60 * 60 * 1000,
      type: "feed",
    },
    {
      id: "34",
      uid: "5",
      text: "Working on a new open source project",
      timestamp: Date.now() - 25 * 60 * 60 * 1000,
      type: "feed",
    },

    // Recommendations
    {
      id: "7",
      uid: "system",
      text: "Breaking: New framework released that will change everything!",
      timestamp: Date.now() - 30 * 60 * 1000,
      type: "recommendation",
    },
    {
      id: "8",
      uid: "system",
      text: "10 UI/UX principles you should know in 2024",
      timestamp: Date.now() - 2 * 60 * 60 * 1000,
      type: "recommendation",
    },
    {
      id: "9",
      uid: "system",
      text: "Join our virtual meetup next week!",
      timestamp: Date.now() - 24 * 60 * 60 * 1000,
      type: "recommendation",
    },
    {
      id: "35",
      uid: "system",
      text: "Top 5 productivity apps you should try",
      timestamp: Date.now() - 3 * 60 * 60 * 1000,
      type: "recommendation",
    },
    {
      id: "36",
      uid: "system",
      text: "Local event: Tech conference this Saturday",
      timestamp: Date.now() - 5 * 60 * 60 * 1000,
      type: "recommendation",
    },
    {
      id: "37",
      uid: "system",
      text: "New study shows benefits of meditation for developers",
      timestamp: Date.now() - 8 * 60 * 60 * 1000,
      type: "recommendation",
    },

    // Chat messages - updated to use new room IDs
    {
      id: "10",
      uid: "1",
      text: "Hey, how are you doing?",
      timestamp: Date.now() - 2 * 60 * 60 * 1000,
      type: "chat",
      room: "private-1-0",
    },
    {
      id: "11",
      uid: "0",
      text: "I'm good! Working on the new project.",
      timestamp: Date.now() - 118 * 60 * 1000,
      type: "chat",
      room: "private-1-0",
    },
    {
      id: "12",
      uid: "1",
      text: "That sounds exciting! Let me know if you need help.",
      timestamp: Date.now() - 115 * 60 * 1000,
      type: "chat",
      room: "private-1-0",
    },
    {
      id: "38",
      uid: "0",
      text: "Thanks! I'll definitely reach out if I get stuck",
      timestamp: Date.now() - 110 * 60 * 1000,
      type: "chat",
      room: "private-1-0",
    },
    {
      id: "39",
      uid: "1",
      text: "Great! Looking forward to seeing what you build",
      timestamp: Date.now() - 105 * 60 * 1000,
      type: "chat",
      room: "private-1-0",
    },

    // Notifications
    {
      id: "13",
      uid: "system",
      text: "Alice Johnson liked your post",
      timestamp: Date.now() - 5 * 60 * 1000,
      type: "notification",
      subtype: "like",
    },
    {
      id: "14",
      uid: "system",
      text: "Bob Smith started following you",
      timestamp: Date.now() - 15 * 60 * 1000,
      type: "notification",
      subtype: "follow",
    },
    {
      id: "15",
      uid: "system",
      text: "Carol Davis commented on your photo: 'Great shot!'",
      timestamp: Date.now() - 45 * 60 * 1000,
      type: "notification",
      subtype: "comment",
    },
    {
      id: "40",
      uid: "system",
      text: "David Wilson shared your post",
      timestamp: Date.now() - 55 * 60 * 1000,
      type: "notification",
      subtype: "share",
    },
    {
      id: "41",
      uid: "system",
      text: "Emma Brown mentioned you in a comment",
      timestamp: Date.now() - 65 * 60 * 1000,
      type: "notification",
      subtype: "mention",
    },
    {
      id: "42",
      uid: "system",
      text: "Frank Miller sent you a friend request",
      timestamp: Date.now() - 75 * 60 * 1000,
      type: "notification",
      subtype: "friend-request",
    },

    // Popular posts
    {
      id: "16",
      uid: "4",
      text: "This new framework is trending everywhere! #webdev",
      timestamp: Date.now() - 60 * 60 * 1000,
      type: "popular",
    },
    {
      id: "17",
      uid: "5",
      text: "Breakthrough in machine learning algorithms announced today",
      timestamp: Date.now() - 2 * 60 * 60 * 1000,
      type: "popular",
    },
    {
      id: "43",
      uid: "6",
      text: "Viral recipe for the best chocolate chip cookies!",
      timestamp: Date.now() - 3 * 60 * 60 * 1000,
      type: "popular",
    },
    {
      id: "44",
      uid: "7",
      text: "The most beautiful hiking trails in the country",
      timestamp: Date.now() - 4 * 60 * 60 * 1000,
      type: "popular",
    },
    {
      id: "45",
      uid: "8",
      text: "How I built a million-dollar business in 6 months",
      timestamp: Date.now() - 6 * 60 * 60 * 1000,
      type: "popular",
    },
    {
      id: "46",
      uid: "9",
      text: "The secret to maintaining work-life balance",
      timestamp: Date.now() - 8 * 60 * 60 * 1000,
      type: "popular",
    },
    {
      id: "47",
      uid: "10",
      text: "My journey from zero to 100k followers on social media",
      timestamp: Date.now() - 12 * 60 * 60 * 1000,
      type: "popular",
    },
  ]
